apiVersion: v1
kind: Pod
metadata:
  name: order-api
  namespace: orders-module
  labels:
    app: order-api
    tier: backend
    env: testing
spec:
  containers:
    - name: order-api
      image: 192.168.88.5:8086/udemy/ecommerce-order:v2
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 9091
          name: http
      envFrom:
        - configMapRef:
            name: order-api
      env:
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              key: POSTGRES_USER
              name: postgres
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: POSTGRES_PASSWORD
              name: postgres
        - name: DATABASE_HOST
          value: postgres
        - name: DATABASE_PORT
          value: "5432"
        - name: DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_DB
              name: postgres
      startupProbe:
        httpGet:
          port: http
          path: /actuator/health/readiness
        initialDelaySeconds: 2
        timeoutSeconds: 1
      livenessProbe:
        httpGet:
          port: http
          path: /actuator/health/liveness
        periodSeconds: 5
        timeoutSeconds: 1
        failureThreshold: 3
  restartPolicy: Always
