apiVersion: v1
kind: Pod
metadata:
  name: mysql
  namespace: customer-module
  labels:
    app: mysql
    tier: database
    env: testing
spec:
  containers:
    - name: mysql
      image: 192.168.88.50:8086/mysql:8.0
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 3306
          name: tcp
      envFrom:
        - secretRef:
            name: mysql
        - configMapRef:
            name: mysql
  restartPolicy: Always
