apiVersion: v1
kind: Pod
metadata:
  name: postgres
  namespace: orders-module
  labels:
    app: postgres
    tier: database
    env: testing
spec:
  containers:
    - name: postgres
      image: 192.168.88.5:8086/postgres:15
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 5432
          name: tcp
      envFrom:
        - configMapRef:
            name: postgres
        - secretRef:
            name: postgres
  restartPolicy: Always
