apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: orders-module
spec:
  selector:
    app: postgres
    tier: database
    env: testing
  ports:
    - port: 5432
      name: tcp
      protocol: TCP
  type: ClusterIP